feat(main): add appBar, BottomNavigationBar, FAB, content
KateF28/tails_app pull request #4
Opened 2023-10-09 18:49 UTC by KateF28

Add appBar, BottomNavigationBar and FAB for breeds list and grid display. Add StatelessWidget widget for the selected breed.

2023-10-09 21:51 UTC, VadymPinchuk requested changes

2023-10-09 21:51 UTC, VadymPinchuk commented on lib/presentation/views/home_view.dart
> +// Models:
коменти в імпортах краще не робити )

2023-10-09 21:51 UTC, VadymPinchuk commented on lib/presentation/views/home_view.dart
> +var uuid = const Uuid();
це публічно доступна глобальна змінна. По можливості такого краще уникати

2023-10-09 21:51 UTC, VadymPinchuk commented on lib/presentation/views/home_view.dart
> +            ? SliverList.builder(
занадто велика вкладеність. краще винести сліверЛіст в функцію яка його поверне

2023-10-09 21:51 UTC, VadymPinchuk commented on lib/presentation/views/home_view.dart
> +                        child: Image.asset(_breeds[index].imgUrl,
треба відформатувати код.

2023-10-09 21:51 UTC, VadymPinchuk commented on lib/presentation/views/home_view.dart
> +                          _breeds = _breeds.map((breed) {
це дуже дорога операція. На даному етапі ок, але в майбутньому таке краще не робити ) оскільки ліст може мати багато елементів

2023-10-09 21:51 UTC, VadymPinchuk commented on lib/presentation/views/home_view.dart
> +            : SliverGrid.builder(
в окремий метод

2023-10-09 21:51 UTC, VadymPinchuk commented on lib/presentation/views/home_view.dart
> +                      _breeds = _breeds.map((breed) {
логіка багато де повторюється. якщо є можливість перевикористати - треба винести логіку в окремий метод і перевикористати ) і код стане красивіший і читабельніший.і не буде повторень

2023-10-09 21:51 UTC, VadymPinchuk commented on lib/presentation/views/home_view.dart
> +                              image: AssetImage(_breeds[idx].imgUrl))),
коми перед дужками дуже гарно б змінили форматування

2023-10-09 22:35 UTC, KateF28 commented on lib/presentation/views/home_view.dart
> +                          _breeds = _breeds.map((breed) {
Не знаю як було б краще тут

2023-10-10 10:24 UTC, VadymPinchuk requested changes

2023-10-10 10:24 UTC, VadymPinchuk commented on lib/presentation/views/home_view.dart
> +        ..._breeds.map((breed) => breed.isSelected
Так. Нам тут потрібен лише один віджет. Тому що я пропоную - зберігати вибрану породу саме у Стейті даного екрану. І прибрати селекшн з самої моделі Breed. 
Тоді нам не потрібно буде робити мапінг (бо це дорого) а також не потрібно буде заповнювати порожніми віджетами SliverToBoxAdapter(child: SizedBox.shrink())). Нам просто потрібно буде додавати один віджет, якщо є вибрата порода.

2023-10-10 10:24 UTC, VadymPinchuk commented on lib/presentation/views/home_view.dart
> +    setState(() {
і тоді ось цей метод весь також зміниться. НАм не потрібно змінювати весь ліст даних (хороший тон робити їх незмінними - immutable)

а лише зберігати обрану породу в _HomeViewState. Ефективно )

2023-10-10 21:38 UTC, VadymPinchuk approved these changes

2023-10-10 21:38 UTC, VadymPinchuk commented on lib/presentation/views/home_view.dart
> +            : const SliverToBoxAdapter(child: SizedBox.shrink()),
Не думаю що цей віджет взагалі потрібен

2023-10-10 21:38 UTC, VadymPinchuk commented on lib/presentation/views/home_view.dart
> +                _breeds = breedsList
Виключно питання стейт менеджменту, але я б подивився чи потрібно цей елемент видаляти із списку саме таким чином. Чи потрібно робити setState(). Це питання більше на роздуми

2023-10-10 21:38 UTC, VadymPinchuk commented on lib/presentation/views/home_view.dart
> +            const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 2),
кома перед фінальною дужкою зробила б гарний форматінг )

2023-10-10 21:38 UTC, VadymPinchuk commented on lib/presentation/views/home_view.dart
> +              ]),
і тут також

2023-10-10 21:38 UTC, merged