feat(main): add FutureBuilder, mock_api, compute, animation
KateF28/tails_app pull request #7
Opened 2023-10-26 14:15 UTC by KateF28

2023-10-28 22:39 UTC, VadymPinchuk requested changes
Бачу певні лаги в UI - повʼязані із видаленням. Варто переглянути чому так відбувається. З точки зору прикладу - все ніби гарно. Але відправлю на допрацювання щоб знайшла помилку

2023-10-29 15:32 UTC, VadymPinchuk requested changes

2023-10-29 15:32 UTC, VadymPinchuk commented on lib/presentation/views/home_view.dart
> +  Future<void> _removedBreedsCount() async {
Назва методу як і параметра у Класі - доволі незрозуміла. Count - складається враження що це має бути поле типу int

2023-10-29 15:32 UTC, VadymPinchuk commented on lib/presentation/widgets/breeds_list.dart
> +  const BreedsList({super.key, required this.removedBreedsCount});
ось цей параметр у конструкторі як і член класу - трохи бентежать саме назвою

2023-10-29 15:32 UTC, VadymPinchuk commented on lib/presentation/widgets/breeds_list.dart
> +                    breedsSnapshot.removeAt(index);
ось це зайве. оскільки ми по факту модифікуємо список який використовуємо локально. але глобально змінює список якраз наступний метод. і після того - ми отримуємо сюди уже оновлений список

2023-10-29 15:32 UTC, VadymPinchuk commented on lib/presentation/widgets/breeds_list.dart
> +                    await widget.removedBreedsCount();
в ідеалі тут має викликатись один метод. а уже логіка обробки цього функціоналу має бути винесена вище ( в парент віджет) або ж у репозиторій.  Краще винести в репозиторій. він оновить список.

2023-10-29 15:45 UTC, KateF28 commented on lib/presentation/widgets/breeds_list.dart
> +                    breedsSnapshot.removeAt(index);
Без цього Exception: A dismissed Dismissible widget is still part of the tree.
Але ок, я видалю

2023-10-29 16:31 UTC, VadymPinchuk approved these changes

2023-10-29 16:31 UTC, merged